version: '3'
services:

  splunk:
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: changeme123
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    networks:
      - splunk-net

  dvwa:
    build: .
    ports:
      - "8081:80"
    networks:
      - splunk-net
    depends_on:
      - splunk

networks:
  splunk-net:
    driver: bridge